version: "3.8"

services:
  app:
    container_name: blind-sqli
    build: .
    volumes:
      - .:/var/www/html/
    ports:
      - "3820:80"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql
    container_name: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootadalahakar
      - MYSQL_DATABASE=country_simple_mysqli
      - MYSQL_USER=mysqliyes
      - MYSQL_PASSWORD=mysqlino
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
